### ISSUE TITLE
Protégé 5 inconsistent ontology error with Act_of_Law part Mandate

### ISSUE THREAD

**Issue by jziemer2** [RinkeHoekstra/lkif-core#3]
Hi Rinke,
Many years since publication and still the best Legal Ontology. I am populating LKIF with US financial laws & regulations:
Part of (mereo:part) the US Dodd-Frank Wall St. reform Act (laction:Act_of_Law) is the Supervisory Mandate for the Securities & Exchange Commission (laction:Mandate).
When I instantiate these triples (us-instance.ttl) and start the Reasoner, Protégé 5 throws an inconsistent ontology error (screenshot.jpg). The Act_of_Law gets inferred as action:Plan, which is disjoint with action.
1)  What is the best resolution? Making Plan Equivalence to more restrictive works: mereo:part some action:Action and not laction:Act_of_Law
2)  How do you best connect one laction:Public_Act to another? I tried process:result_of, but it also throws an error (Change DisjointWith Physical_Object).  

Can you advise? Many thanks
Jurgen

[LKIF_US_instance_TTL.txt](https://github.com/RinkeHoekstra/lkif-core/files/326426/LKIF_US_instance_TTL.txt)

![lkif us instance - protege inconsitent ontology explaination screenshot](https://cloud.githubusercontent.com/assets/11173121/16243180/035bed66-37c4-11e6-98a2-560479294658.jpg)

**Comment by RinkeHoekstra** [comment]
Hi Jurgen,
Glad to hear LKIF Core is of some use to you. My grasp of what we did is a bit rusty, so forgive me if this is not entirely correct:

Indeed LKIF specifies that `action:Plan` is equivalent to anything that has `action:Action` as its parts. This  is not very intuitive, as one could imagine that actions themselves can be decomposed into sub-actions. In designing LKIF Core, we decided to model that mereology through the plan (as is similar to e.g. in PROV-O). 

That said... I think there is a way out in that the `laction:Act_of_Law` is meant as e.g. the actual enactment of legislation, and not the legal act in the sense of a document that reflects a legal action. If you were to model the act and the mandate as documents rather than actions, things should work out.

Does that help?

**Comment by jziemer2** [comment]
Thanks so much Rinke,
For your fast response and advice resolving the issue. 

Indeed the Act-Mandate relation must not be mereological.  Rephrase: _The US Dodd-Frank Wall Street reform Act (`laction:Act_of_Law`) is a `process:requirement_of` the Supervisory Mandate for the Securities & Exchange Commission (`laction:Mandate`)._ And LKIF will classify.

Yes, the United State Code (USC) and the Code of Federal Regulation (CFR) are `norm:Statute` and `norm:Regulation`. The mereology of subclasses for title, chapter, section, paragraph, note, citation works well. And finally _the US Dodd-Frank Act `expression:bears`the document USC Title 15 Subchapter 2D Investment Advisers._
Regards
Jurgen
